# Generated by Django 4.0.4 on 2022-05-16 20:37

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=205)),
                ('date_create', models.DateField(default=datetime.datetime(2022, 5, 16, 20, 37, 14, 490682, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='AddMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=150)),
                ('date_create', models.DateField(default=datetime.datetime(2022, 5, 16, 20, 37, 14, 489687, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=250)),
                ('date_create', models.DateField(default=datetime.datetime(2022, 5, 16, 20, 37, 14, 491674, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.DateField(default=datetime.datetime(2022, 5, 16, 20, 37, 14, 488695, tzinfo=utc))),
                ('date_create', models.DateField(default=datetime.datetime(2022, 5, 16, 20, 37, 14, 488695, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='BestMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=150)),
                ('number_person', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(999)])),
                ('date_create', models.DateField(default=datetime.datetime(2022, 5, 16, 20, 37, 14, 491674, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('number_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=150)),
                ('date_create', models.DateField(default=datetime.datetime(2022, 5, 16, 20, 37, 14, 492667, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='LinkReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('pinterest', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('date_create', models.DateField(default=datetime.datetime(2022, 5, 16, 20, 37, 14, 488695, tzinfo=utc))),
            ],
        ),
    ]
