# Generated by Django 4.0.4 on 2022-05-16 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 20, 46, 21, 878516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 20, 46, 21, 877523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 20, 46, 21, 879509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='background_image',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 20, 46, 21, 876529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 20, 46, 21, 876529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 20, 46, 21, 878516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 20, 46, 21, 880503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 20, 46, 21, 875538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
