# Generated by Django 4.0.4 on 2022-05-16 21:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_aboutindex_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 21, 54, 1, 790312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 21, 54, 1, 789319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 21, 54, 1, 791305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='background_image',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 21, 54, 1, 787332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 21, 54, 1, 787332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 21, 54, 1, 791305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 21, 54, 1, 792299, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 21, 54, 1, 786339, tzinfo=utc)),
        ),
    ]
