# Generated by Django 4.0.4 on 2022-05-16 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_aboutindex_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 26, 2, 640885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 26, 2, 638899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 26, 2, 641879, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='background_image',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 26, 2, 637905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 26, 2, 637905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 26, 2, 641879, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 26, 2, 643866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 22, 26, 2, 636912, tzinfo=utc)),
        ),
    ]
