# Generated by Django 4.0.4 on 2022-05-17 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_remove_contactus_message_contactus_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkreseau',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 12, 42, 38, 685922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 12, 42, 38, 684414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 12, 42, 38, 684059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 12, 42, 38, 685100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 12, 42, 38, 683389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 12, 42, 38, 684783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 12, 42, 38, 685465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 12, 42, 38, 682639, tzinfo=utc)),
        ),
    ]
