# Generated by Django 4.0.4 on 2022-05-17 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_addmenu_type_food_alter_aboutindex_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 17, 26, 181081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 17, 26, 180089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='type_food',
            field=models.CharField(choices=[('burger', 'burger'), ('pizza', 'pizza'), ('pasta', 'pasta'), ('fries', 'fries')], default='Burger', max_length=10),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 17, 26, 183068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 17, 26, 176115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 17, 26, 182075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 17, 26, 184061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linkreseau',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 17, 26, 185055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 17, 26, 174127, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Solds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.addmenu')),
            ],
        ),
    ]
