# Generated by Django 4.0.4 on 2022-05-17 21:32

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_alter_aboutindex_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solds',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 694725, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='solds',
            name='reduction',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 690751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 690751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 692738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 688765, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 691745, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 693731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linkreseau',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 693731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 32, 16, 687771, tzinfo=utc)),
        ),
    ]
