# Generated by Django 4.0.4 on 2022-05-17 21:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_solds_date_create_solds_reduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(100)])),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 564998, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 561025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 560032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 562019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 558046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 562019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 563012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linkreseau',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 564006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 39, 9, 557052, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Solds',
        ),
        migrations.AddField(
            model_name='sold',
            name='menu_sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.addmenu'),
        ),
    ]
