# Generated by Django 4.0.4 on 2022-05-17 21:44

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_sold_alter_aboutindex_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 258987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 257994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 259981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 257001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 259981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 260974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linkreseau',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 260974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 256007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 44, 23, 261967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='menu_sold',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sold',
            name='reduction',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
