# Generated by Django 4.0.4 on 2022-05-17 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_alter_aboutindex_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='day_special',
            field=models.CharField(choices=[('Pizza day', 'Pizza day'), ('Burger day', 'Burger day'), ('Pasta day', 'Pasta day'), ('Fries day', 'Fries day')], default='r', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 102639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 101645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 103632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 100652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 102639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 104625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linkreseau',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 105619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 99659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 21, 49, 49, 106613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='menu_sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.addmenu'),
        ),
    ]
