# Generated by Django 4.0.4 on 2022-05-19 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_sold_day_special_alter_aboutindex_date_create_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestMenu',
        ),
        migrations.AlterField(
            model_name='aboutindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 929793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 929425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avisclient',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 930476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='backgroundimageindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 928982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 930159, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 930827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linkreseau',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 931285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sliderindex',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 928267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 44, 34, 931622, tzinfo=utc)),
        ),
    ]
